edition = "2024"
unstable_features = true

max_width = 80
match_arm_blocks = false
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
overflow_delimited_expr = true
enum_discrim_align_threshold = 20
group_imports = "StdExternalCrate"
struct_field_align_threshold = 5
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true